default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: ecommerce-prototype-rails_development

test:
  <<: *default
  database: ecommerce-prototype-rails_test

production:
  <<: *default
  database: ecommerce-prototype-rails_production
  username: ecommerce-prototype-rails
  password: <%= ENV['ECOMMERCE-PROTOTYPE-RAILS_DATABASE_PASSWORD'] %>
